"""
Configuration script for the hyphi toolbox.

This module is designed to work both inside the hyphi repository itself and when hyphi is installed
(e.g., via pip) as a dependency of another project. It discovers the *using* project's root by walking
up from the current working directory looking for a `.git` folder or `pyproject.toml`, then searches
for `<project_root>/configs/*config.toml`.

Usage:
-----
    >>> from hyphi.configs import config
    >>> config.init()  # loads configs/*config.toml, creating a default if none exist

Note:
----
    * private configs live in the same folder as 'config.toml' and start with an underscore,
      e.g., "_config.toml" or "_secret_config.toml". Files starting with "_" are git-ignored and
      are loaded last, so they override the public configs.
    * non-private files such as "experiment_config.toml" are tracked by git.

Alternatives:
-----------
    * load *configs.toml's with the toml module (see below) and process it further with the package python-box
    * configs could also be set using an .env file together with the python-dotenv package.

Author: Simon M. Hofmann
GitHub: SHEscher
Years: 2023 & 2026

"""

# %% Imports
from __future__ import annotations

import logging.config
import os
import tomllib as toml  # expects python>=3.11
from pathlib import Path
from typing import Any

# %% Project-root discovery & default config ><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o

# Markers used to detect the root of the project that uses hyphi (walking up from the CWD)
_PROJECT_ROOT_MARKERS = (".git", "pyproject.toml")

# Subfolder (relative to the project root) where config.toml file(s) are searched for / created
_CONFIG_SUBDIR = "configs"

# Top-level keys a valid hyphi config must provide (used to detect "foreign" config files)
_REQUIRED_KEYS = ("PROJECT_NAME", "paths", "params", "logging")

# Template for an auto-generated config.toml. The '__PROJECT_NAME__' and '__LOG_NAME__'
# placeholders are substituted at creation time (str.format is avoided because of the '{...}'
# logging-format strings below).
_DEFAULT_CONFIG_TEMPLATE = """# Config file auto-generated by hyphi.configs.config.init().
# Drop all relevant paths, parameters, etc. here.
# They can be accessed in the code via:
#   from hyphi.configs import config
#   config.init()
# Headers `[paths]` or `[myconfigsection]` (see below) can be accesed via:
#   config.paths
#   config.myconfigsection
# Note, store private configs in the same folder as this file with a leading underscore,
# e.g. "_config.toml" or "_secret_config.toml". These should be git-ignored!
# Private configs are loaded last (so they override these public settings).

PROJECT_NAME = "__PROJECT_NAME__" # used for paths, logging, etc. Adapt to your liking.

# Set paths
[paths]
# all paths are relative to the PROJECT_ROOT folder (the folder that uses hyphi)
DATA = "./data"
RESULTS = "./results"
CACHE = "./data/cache"

[paths.results]
visualizations = "./results/datavisualization"

# Set parameters
[params]
weight_decay = 0.01 # TODO: replace PLACEHOLDER, and add relevant parameters

################################################
##################  LOGGER  ####################
################################################

# Set logging
[logging]
version = 1                      # currently only version 1
disable_existing_loggers = false

[logging.formatters.fmtfile]
# Format for file handler
format = "{asctime:23} :: {name} :: {levelname:^8} :: {message}"
style = "{"

[logging.formatters.console]
# Format for console handler (StreamHandler)
format = "\\n\\t{asctime:19} :: {name} :: {levelname:^8} :: {message}\\n"
style = "{"
datefmt = "%Y-%m-%d %H:%M:%S"

[logging.handlers.file_handler]
level = "DEBUG"                  # == 10 (pass int or string)
formatter = "fmtfile"
filename = "logs/__LOG_NAME__.log" # parent dir is created automatically
class = "logging.FileHandler"    # for file output

[logging.handlers.stream_handler]
level = "INFO"
formatter = "console"
class = "logging.StreamHandler" # for console output

[logging.loggers.__main__] # __name__ of the calling module
level = "INFO" # handlers can have different levels
# logging.DEBUG == 10 < ...INFO == 20 < WARNING == 30 < ERROR == 40 < CRITICAL == 50
propagate = true
handlers = ["file_handler", "stream_handler"]
"""


def _find_project_root(start: str | Path | None = None) -> Path:
    """
    Find the root of the project that uses hyphi.

    Walks up from `start` (default: current working directory) until a directory containing one of
    `_PROJECT_ROOT_MARKERS` is found. Falls back to `start` if no marker is found.

    :param start: directory to start the upward search from (default: CWD)
    :return: the discovered project root path
    """
    start = Path(start or Path.cwd()).absolute()
    for path in (start, *start.parents):
        if any((path / marker).exists() for marker in _PROJECT_ROOT_MARKERS):
            return path
    return start


def _create_default_config(config_dir: Path, project_name: str) -> Path:
    """
    Create a default `config.toml` in `config_dir`.

    :param config_dir: directory in which to create the config file (created if missing)
    :param project_name: value to use for `PROJECT_NAME` in the new config file
    :return: path to the newly created config file
    """
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config.toml"
    content = _DEFAULT_CONFIG_TEMPLATE.replace("__PROJECT_NAME__", project_name).replace(
        "__LOG_NAME__", project_name.lower()
    )
    config_path.write_text(content, encoding="utf-8")
    print("\033[93m" + f"Created a default hyphi config at:\n\t{config_path}" + "\033[0m")  # yellow
    return config_path


def _discover_config_files(config_dir: Path) -> list[Path]:
    """
    Find all `*config.toml` files in `config_dir`.

    Public configs (not starting with `_`) are returned first, private configs (starting with `_`)
    last, so that private configs override public ones when loaded in order.

    :param config_dir: directory to search for config files
    :return: ordered list of config file paths (public first, private last); empty if the directory is missing
    """
    if not config_dir.is_dir():
        return []
    files = sorted(config_dir.glob("*config.toml"))
    public = [f for f in files if not f.name.startswith("_")]
    private = [f for f in files if f.name.startswith("_")]
    return public + private


# %% Config class & functions ><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o


def _iter_nested_dicts(nested_dict: dict[str, Any]) -> Any:
    """Create a generator iterating over values in nested dicts."""
    for value in nested_dict.values():
        if isinstance(value, dict):
            yield from _iter_nested_dicts(value)
        else:
            yield value


def _create_parent_dirs(config_as_dict: dict[str, Any]) -> None:
    """Create parent dirs of log files."""
    for value in _iter_nested_dicts(config_as_dict):
        if isinstance(value, str) and value.endswith(".log"):
            Path(PROJECT_ROOT, value).parent.mkdir(parents=True, exist_ok=True)


class _CONFIG:
    """Configuration object."""

    def __init__(self, config_dict: dict | None = None):
        """Initialize _CONFIG class object."""
        if config_dict is not None:
            self.update(config_dict)

    def __repr__(self):
        """Implement __repr__ of _CONFIG."""
        str_out = "_CONFIG("
        list_attr = [k for k in self.__dict__ if not k.startswith("_")]
        ctn = 0  # counter for visible attributes only
        for key, val in self.__dict__.items():
            if key.startswith("_"):
                # ignore hidden attributes
                continue
            ctn += 1
            str_out += f"{key}="
            if isinstance(val, _CONFIG):
                str_out += val.__str__()
            else:
                str_out += f"'{val}'" if isinstance(val, str) else f"{val}"

            str_out += ", " if ctn < len(list_attr) else ""
        return str_out + ")"

    def init(self, project_name: str | None = None) -> _CONFIG:
        """
        Create the config infrastructure (if missing) and load it.

        Searches for `<project_root>/configs/*config.toml`. If none exist, a default
        `configs/config.toml` is created.

        :param project_name: value for `PROJECT_NAME` when creating a new config (default: root folder name)
        :return: the configured config object (self)
        """
        return _configure(self, project_name=project_name)

    def update(self, new_configs: dict[str, Any]):
        """Update the config object with new entries."""
        for k, val in new_configs.items():
            if isinstance(val, (list, tuple)):
                setattr(self, k, [_CONFIG(x) if isinstance(x, dict) else x for x in val])
            else:
                setattr(self, k, _CONFIG(val) if isinstance(val, dict) else val)

    def show(self, indent: int = 0):
        """
        Display the nested configuration information.

        :param indent: The number of tabs to use for indentation (default: 0)
        :type indent: int
        :return: None
        """
        for key, val in self.__dict__.items():
            if isinstance(val, _CONFIG):
                print("\t" * indent + f"{key}:")
                val.show(indent=indent + 1)
            else:
                _val = val.replace("\n", "\\n").replace("\t", "\\t") if isinstance(val, str) else val
                print("\t" * indent + f"{key}: " + (f"'{_val}'" if isinstance(val, str) else f"{val}"))

    def asdict(self):
        """Convert config object to dict."""
        dict_out = {}
        for key, val in self.__dict__.items():
            if isinstance(val, _CONFIG):
                dict_out.update({key: val.asdict()})
            else:
                dict_out.update({key: val})
        return dict_out

    def update_paths(self, parent_path: str | None = None, for_logging: bool = False):
        """Update relative paths to PROJECT_ROOT dir."""
        # Use the project root dir as the parent path if not specified
        parent_path = self.PROJECT_ROOT if hasattr(self, "PROJECT_ROOT") else parent_path

        if parent_path is not None:
            parent_path = str(Path(parent_path).absolute())

            for key, path in self.__dict__.items():
                if isinstance(path, str) and not Path(path).is_absolute():
                    if for_logging and key != "filename":
                        # In the case of logging configs, apply only on filename
                        continue
                    self.__dict__.update({key: str(Path(parent_path).joinpath(path))})

                elif isinstance(path, _CONFIG):
                    path.update_paths(parent_path=parent_path, for_logging=for_logging)

        else:
            print("\033[91mPaths can't be converted to absolute paths, since no PROJECT_ROOT is found!\033[0m")  # red


def _set_wd(new_dir: str | Path) -> None:
    """
    Set the given directory as the new working directory of the project.

    :param new_dir: name of new working directory (must be in the project folder)
    """
    if not str(Path.cwd().absolute()).startswith(str(Path(PROJECT_ROOT).absolute())):
        msg = f"Current working dir '{Path.cwd()}' is outside of project root '{PROJECT_ROOT}'."
        raise OSError(msg)

    print("\033[94m" + f"Current working dir:\t{Path.cwd()}" + "\033[0m")  # print blue

    # Check if new_dir is a folder path or just a folder name
    new_dir = Path(new_dir)
    if new_dir.is_absolute():
        found = new_dir.is_dir()
        change_dir = new_dir.absolute() != Path.cwd()
        if found and change_dir:
            os.chdir(new_dir)

    else:
        # Remove '/' if new_dir == 'folder/' OR '/folder'
        new_dir = new_dir.name

        # Check if new_dir is the current dir
        found = new_dir == Path.cwd().name
        change_dir = not found

        # First look down the tree
        if not found:
            # Note: This works only for unique folder names
            paths_found = sorted(Path(PROJECT_ROOT).parent.glob(f"**/{new_dir}"), key=lambda x: len(x.parents))
            if len(paths_found) > 1:
                msg = (
                    f"Found multiple folders with name '{new_dir}' in project '{PROJECT_NAME}'!\n\n"
                    f"Please specify the absolute path to the desired folder:\n\n{[str(p) for p in paths_found]}"
                )
                raise ValueError(msg)

            if len(paths_found) == 1:
                found = True
                os.chdir(paths_found.pop())

    if found and change_dir:
        print("\033[93m" + f"New working dir: '{Path.cwd()}'\n" + "\033[0m")  # yellow print
    elif found and not change_dir:
        pass
    else:
        print("\033[91m" + f"Given folder not found. Working dir remains: '{Path.cwd()}'\n" + "\033[0m")  # red print


# %% Setup configuration object < o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o

# Module-level objects ready for import in other scripts. They remain "empty"/None until either an
# existing config is auto-loaded on import or the user calls `config.init()`.
config = _CONFIG()
PROJECT_ROOT: str = str(_find_project_root())
PROJECT_NAME: str | None = None


def _configure(config_obj: _CONFIG, *, project_name: str | None = None) -> _CONFIG:
    """
    Discover, create (if missing), load and apply the hyphi configuration.

    :param config_obj: the config object to populate (the module-level `config`)
    :param project_name: `PROJECT_NAME` for a newly created config (default: project root folder name)
    :return: the configured config object
    """
    global PROJECT_NAME, PROJECT_ROOT  # noqa: PLW0603 (module-level config singletons)

    project_root = _find_project_root()
    PROJECT_ROOT = str(project_root)
    config_dir = project_root / _CONFIG_SUBDIR

    config_files = _discover_config_files(config_dir)

    # No config file present yet -> inform the user and create a default config
    if not config_files:
        name = project_name or project_root.name
        print(f"No hyphi config found in '{config_dir}'. Creating a default 'config.toml' (PROJECT_NAME='{name}')...")
        config_files = [_create_default_config(config_dir=config_dir, project_name=name)]

    # Load config file(s) (public first, private last so private overrides public)
    for config_file in config_files:
        with config_file.open("rb") as f:
            config_obj.update(new_configs=toml.load(f))

    # Validate that this is actually a hyphi config and not some foreign config.toml
    missing_keys = [k for k in _REQUIRED_KEYS if not hasattr(config_obj, k)]
    if missing_keys:
        print(
            "\033[91m"
            f"Found config file(s) in '{config_dir}', but they do not define the keys hyphi expects "
            f"(missing: {missing_keys}).\n"
            "hyphi was NOT configured and your files were left untouched.\n"
            f"If a file in '{config_dir}' belongs to another tool, move hyphi's config elsewhere or "
            "remove the conflicting file, then call `config.init()` to create a valid hyphi config.\n"
            "Alternatively, add the missing keys to the config file(s) and call `config.init()` again."
            "\033[0m"
        )
        return config_obj

    # Resolve the project root path: an explicit PROJECT_ROOT in the config file takes precedence
    PROJECT_NAME = config_obj.PROJECT_NAME
    if hasattr(config_obj.paths, "PROJECT_ROOT"):
        PROJECT_ROOT = config_obj.paths.PROJECT_ROOT
    else:
        config_obj.paths.PROJECT_ROOT = PROJECT_ROOT
    # Make all relative paths absolute w.r.t. the project root
    config_obj.paths.update_paths()

    # Prepare logging
    config_obj.logging.update_paths(parent_path=PROJECT_ROOT, for_logging=True)
    _create_parent_dirs(config_as_dict=config_obj.logging.asdict())

    # Set logging configs
    logging.config.dictConfig(config_obj.logging.asdict())  # in scripts: import logging & logging.getLogger(__name__)

    # Welcome
    _w = 95
    print("\n" + ("*" * _w + "\n") * 2 + "\n" + f"{PROJECT_NAME:^{_w}}" + "\n" * 2 + ("*" * _w + "\n") * 2)

    # Set the project working directory
    _set_wd(PROJECT_ROOT)

    return config_obj


# o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o >><< o END
